n1 = input("dime n1 ")
n2= input("dime n2 ")
#cambiar todo a int y poner lo d ela f y {}
suma=int(n1)+int(n2)
resta=int(n1)-int(n2)
division=float(n1)/float(n2)
multiplicacion=int(n1)*int(n2)
print(f"suma: {suma}")
print(f"resta: {resta}")
print(f"division: {division}")
print(f"multiplicacion: {multiplicacion}")
